services:
  database:
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    volumes:
      - ./data/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=blog
  blog:
    build: .
    ports:
      - "8090:8090"
    environment:
      - PORT=8090
      - MYSQL_HOST=database
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_SCHEMA=blog
